// <auto-generated />
using BusinessCardApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessCardApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221229003223_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("VirtualCard.Models.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<string>("Office")
                        .HasColumnType("TEXT")
                        .HasColumnName("Cargo");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT")
                        .HasColumnName("SurName");

                    b.Property<int>("Telephone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Contributor");
                });
#pragma warning restore 612, 618
        }
    }
}
